lista = [1, "Hola,", 3.67, [1, 2, 3]]
print(lista)
print(lista[1])
print(lista[-2]) 
lista.append(3.14)
print(lista)
lista.extend(["adios", 50])
print(lista)
lista.insert(2, "casa")
print(lista)
lista.remove(3.67)
print(lista)
lista.pop(0)
print(lista)
lista.reverse()
print(lista)
lista_numerica=[11,3,7,2,8]
lista_numerica.sort()
print (lista_numerica)